### PR TITLE
Chef Changes

### PR DESCRIPTION
**Pull request by Bonczidai**
Signed-off-by: Bonczidai Levente levente.bonczidai@hpe.com

### CODE REVIEW

**Comment by benc-uk** [comment]
@Bonczidai - re the chef-repo and validator.pem problem

It sounds like your **knife.rb** file has some information missing, there should be `validation_key` and `client_key` properties in there, which specify where the pem files are. Below is my knife.rb file as an example.

```
ubuntu@chef12:~$ cat ~/.chef/knife.rb
log_level                :info
log_location             STDOUT
node_name                'admin'
client_key               '/home/ubuntu/.chef/admin.pem'
validation_client_name   'demo-validator'
validation_key           '/home/ubuntu/.chef/demo-validator.pem'
chef_server_url          'https://chef.democloud.org.uk/organizations/demo'
syntax_check_cache_path  '/home/ubuntu/.chef/syntax_check_cache'
cookbook_path [ '/home/ubuntu/chef-repo/cookbooks' ]
```

**Comment by Bonczidai** [comment]
I think in your case it works because `.chef` folder is in root directory, in my case it is under `/root/chef-repo/`:

```
root@Chef:~# cat chef-repo/.chef/knife.rb
current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "admin"
client_key               "#{current_dir}/admin.pem"
validation_client_name   "cloudslang-validator"
validation_key           "#{current_dir}/cloudslang-validator.pem"
chef_server_url          "https://<ip>/organizations/cloudslang"
syntax_check_cache_path  "#{ENV['HOME']}/.chef/syntaxcache"
cookbook_path            ["#{current_dir}/../cookbooks"]
```

WDYT?

**Comment by benc-uk** [comment]
My file is in **/home/ubuntu/.chef**

Yes this is just a different way of doing things, at this point it is much down to personal preference of the chef admin. However if you run `knife configure` it will generate a `knife.rb` file for you and it will not use anything like `current_dir` in there, so I actually thing the Digital Ocean is bad advice.

I think this is not something we should try to solve from the cloudslang side, IMO the knife command should work from any location without the need to cd to a special place first, that's just part of setting up Chef

**Comment by Bonczidai** [comment]
I like your approach -- but still, according to [this](https://docs.chef.io/config_rb_knife.html)

```
The default location in which knife expects to find this file is ~/chef-repo/.chef/knife.rb; use the --config option from the command line to change this location
```

there is a default location (seems like it is ~/.chef) which is part of setting up Chef -- in other cases you have to use the --config flag

The question is that: is there a way to set a new location for `.chef` folder as part of knife config? If not, I think we should support the --config flag (better than the  `cd` approach)

**Pull request merged**
